import type { Formation } from '@/types'

export const formations: Formation[] = [
  {
    slug: 'construction-metallique',
    title: 'Construction Métallique',
    subtitle: 'Spéciale FORMATION en Construction Métallique',
    description: 'Maîtrisez la soudure industrielle, la chaudronnerie et la tuyauterie industrielle avec un stage garanti en entreprise.',
    filieres: ['Soudure industrielle et montage', 'Chaudronnerie et tuyauterie industrielle'],
    price: 350000,
    currency: 'FCFA',
    installments: [
      { amount: 150000, label: "À l'inscription" },
      { amount: 100000, label: '1re mensualité' },
      { amount: 100000, label: '2e mensualité' },
    ],
    badgeText: 'Inscriptions ouvertes',
    skills: [
      'Lire et interpréter des plans techniques',
      'Maîtriser les procédés de soudage (MMA, MIG, TIG)',
      'Fabriquer et assembler des structures métalliques',
      'Installer et maintenir des réseaux de tuyauterie',
      'Respecter les normes de sécurité et de métallurgie',
      'Superviser des chantiers de montage industriel',
    ],
    certificates: ['Travaux en hauteur', 'Monteur et vérificateur d\'échafaudages', 'Secourisme (inclus)'],
    extras: ['Kit de protection (PSA)', 'Polo CFPMIE', 'Casquette', 'Manuels de cours'],
  },
  {
    slug: 'gestion-finances-management',
    title: 'Gestion des Finances & Management',
    subtitle: 'Spéciale FORMATION en Gestion des Finances & Management',
    description: 'Devenez un professionnel polyvalent en comptabilité, secrétariat et management.',
    filieres: ['Sécrétariat bureautique', 'Sécrétariat de direction', 'Comptabilité de gestion', 'Management'],
    price: 250000,
    currency: 'FCFA',
    installments: [
      { amount: 150000, label: "À l'inscription" },
      { amount: 50000, label: '1re mensualité' },
      { amount: 50000, label: '2e mensualité' },
    ],
    badgeText: 'Inscriptions ouvertes',
    skills: [
      'Assurer la gestion comptable et financière',
      'Maîtriser les logiciels de bureautique et comptabilité',
      'Gérer la paie, déclarations fiscales et sociales',
      'Organiser et planifier le travail d\'une équipe',
      'Assurer le secrétariat et l\'accueil',
      'Élaborer des rapports et tableaux de bord',
    ],
  },
  {
    slug: 'electricite',
    title: 'Électricité',
    subtitle: 'Spéciale FORMATION en Électricité',
    description: 'Spécialisez-vous en électricité bâtiment et industrielle.',
    filieres: ['Électricité bâtiment', 'Électricité industrielle'],
    price: 350000,
    currency: 'FCFA',
    installments: [
      { amount: 150000, label: "À l'inscription" },
      { amount: 100000, label: '1re mensualité' },
      { amount: 100000, label: '2e mensualité' },
      { amount: 100000, label: '3e mensualité' },
    ],
    badgeText: 'Inscriptions ouvertes',
    skills: [
      'Lire et interpréter des schémas électriques',
      'Réaliser le câblage et les raccordements',
      'Effectuer la maintenance et le dépannage',
      'Installer des tableaux et armoires électriques',
      'Respecter les normes de sécurité électrique',
      'Travailler sur installations bâtiment et industrielles',
    ],
    certificates: ['Habilitation électrique', 'Travaux en hauteur', 'Monteur et vérificateur d\'échafaudages', 'Secourisme (inclus)'],
    extras: ['Kit de protection (PSA)', 'Polo CFPMIE', 'Casquette', 'Manuels de cours'],
  },
]
