// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/formations/construction-metallique": {
    params: {};
  };
  "/formations/gestion-finances-management": {
    params: {};
  };
  "/formations/electricite": {
    params: {};
  };
  "/a-propos": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/formations/construction-metallique" | "/formations/gestion-finances-management" | "/formations/electricite" | "/a-propos" | "/contact" | "/*";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/ConstructionMetallique.tsx": {
    id: "pages/ConstructionMetallique";
    page: "/formations/construction-metallique";
  };
  "pages/GestionFinances.tsx": {
    id: "pages/GestionFinances";
    page: "/formations/gestion-finances-management";
  };
  "pages/Electricite.tsx": {
    id: "pages/Electricite";
    page: "/formations/electricite";
  };
  "pages/About.tsx": {
    id: "pages/About";
    page: "/a-propos";
  };
  "pages/Contact.tsx": {
    id: "pages/Contact";
    page: "/contact";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Home": typeof import("./src/pages/Home.tsx");
  "pages/ConstructionMetallique": typeof import("./src/pages/ConstructionMetallique.tsx");
  "pages/GestionFinances": typeof import("./src/pages/GestionFinances.tsx");
  "pages/Electricite": typeof import("./src/pages/Electricite.tsx");
  "pages/About": typeof import("./src/pages/About.tsx");
  "pages/Contact": typeof import("./src/pages/Contact.tsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.tsx");
};